version: '3.8'

services:
  orders-api:
    build:
      context: ./orders-api
      dockerfile: ../dockerfiles/Dockerfile.fastapi
    command: uvicorn orders_api.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./orders-api:/app
    ports:
      - 8000:8000
    environment:
      - DEPLOYED_ENVIRONMENT=DEV
    depends_on:
      - database

  database:
    build:
      context: ./postgres
      dockerfile: ../dockerfiles/Dockerfile.postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres