FROM python:3.9.6-slim-buster

# For installs without user interaction
ENV DEBIAN_FRONTEND=noninteractive

# Prevents Python from writing pyc files to disc (equivalent to python -B)
ENV PYTHONDONTWRITEBYTECODE=1

# Prevents Python from buffering stdout and stderr (equivalent to python -u)
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update \
    && apt-get -y install netcat gcc libpq-dev graphviz \
    && apt-get clean
# Note: libpq-dev is for Postgres and graphviz is for 'eralchemy' ER diagrams

# Update pip before we install anything
RUN pip3 install --upgrade pip

# Install Poetry
RUN pip3 install poetry==1.1.8
ENV POETRY_VIRTUALENVS_CREATE=false
# Note: Installing with pip allows us to easily fix version #

# Set workdir and copy over files
WORKDIR /app
COPY . .

# Install python dependencies
RUN poetry install --no-dev --no-root --no-interaction

# Make our entrypoint script executable - this file helps us wait for Postgres
# To be ready before starting the server
RUN chmod +x docker_entrypoint.sh